numpy.maximum()
- 두 개의 배열을 가져와 요소별 최댓값 계산
- boradcasting 될 수 있

In [1]:
import numpy as np
a = np.array([3,6,1])
b = np.array([4,2,9])

print(np.maximum(a,b))

[4 6 9]


In [8]:
a = np.arange(1,10).reshape(3,3)

print(a)

print(np.median(a,axis=0))
print(np.median(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
5.0


In [11]:
print(np.var(a,0))
print(np.var(a))

print(np.std(a))
print(f'{np.std(a):.2f}')


[6. 6. 6.]
6.666666666666667
2.581988897471611
2.58


## 최솟값, 최대값 아규먼트 위치
- numpy.argmax(): 제일 큰 갑 위치 정보
- numpy.argmin(): 제일 작은 갑 위치 정보
- numpy.where(조건): 조건에 맞는 값 위치 정보
- numpy.where(조건, 조건에 맞을때 값, 조건과 다를때 값): 조건 결과에 따른 원소 값 변경 

In [13]:
a = np.array([5,7,9,8,1,9,3,4])
#가장 큰 값의 위치 정보(인덱스값)

print(np.argmax(a))
print(np.argmin(a))

2
4


In [16]:
#5를 초ㅘ하는 위치 정보
print(np.where(a>5))
#5를 초과하는 위치는1, 아니면 -1
print(np.where(a>5,1,-1))
print(np.where(a>5,a,0))

(array([1, 2, 3, 5], dtype=int64),)
[-1  1  1  1 -1  1 -1 -1]
[0 7 9 8 0 9 0 0]


## 비교연산
- ==,!=,>=,<=,>,<

In [18]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([3,2,5])

print(a == b)

print(a == c)

[ True  True  True]
[False  True False]


In [20]:
a = np.arange(1,10).reshape(3,3)

result = a % 2 == 0
print(result)
print(a[result])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


numpy.all(),numpy.any()
- all(): 전체 요소가 같아야 하나의 True값을 반환
- any(): 전체 요소중 하나만 같아도 True값을 반환

In [23]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([3,2,5])

print(np.all(a == b))

print(np.all(a == c))

print(np.any(a == b))

True
False
True


##논리연산
- numpy.logical_and(), logical_or(), logical_not(), logical_xor()

In [30]:
x= np.arange(1,11).reshape(2,5)
print(x)
print('-'*30)

y = x%2 == 0
print(y)
print('-'*30)

z = x >= 4
print(z)
print('-'*30)

print('y and z 행렬')
print(np.logical_and(y,z))
print('y and z 행렬의 총합')
print(np.sum(x[np.logical_and(y,z)]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
------------------------------
[[False  True False  True False]
 [ True False  True False  True]]
------------------------------
[[False False False  True  True]
 [ True  True  True  True  True]]
------------------------------
y and z 행렬
[[False False False  True False]
 [ True False  True False  True]]
y and z 행렬의 총합
28


## 정렬

In [31]:
import numpy as np

np.random.seed(10)
data= np.random.randint(1,50,10)
print(data)

[10 37 16  1 29 26 30 49 30  9]


- numpy.sort(): 데이터를 오름차순으로 정렬한다
- 내림차순으로 정렬하는 별도의 옵션은 없다.

In [33]:
np.sort(data)[::-1]

array([49, 37, 30, 30, 29, 26, 16, 10,  9,  1])

- numpy.argsort(): 오름차순으로 정렬한 데이터의 정렬전 인덱스 값을 반환

In [35]:
np.argsort(data)
idx = np.argsort(data)
print(data[idx])

[ 1  9 10 16 26 29 30 30 37 49]


## [문제] 학생 이름과 점수 데이터를 이용하여 성적이 우수한 학생 순서로 이름을 출력하시

In [55]:
name = ['홍길동','저팔계','사오정','전우치','삼장법사']
score = [75,100,95,56,99]
name = np.array(name)
score = np.array(score)
sorted_index = np.argsort(score)[::-1]
print(name[sorted_index])
# print(np.argsort(score))
# idx = np.sort(score)[::-1]
# print(idx)
# print(name[idx])

['저팔계' '삼장법사' '사오정' '홍길동' '전우치']


## 행렬연산

## * 연산자
- 형태(shpae)이 동일한 두 행렬을 원소끼리(element-wise) 곱하는 연산자
- shpae이 다르면 오류 발생
- **교환법칙이 성립된다**


In [61]:
import numpy as np

A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
C = np.array([[2,4],[5,2]])


print(A*B*C)

A = np.arange(6).reshape(2,3)
B = np.arange(6).reshape(3,2)
# print(A*B) shape 이 달라서 오류


[[4 0]
 [0 8]]


## numpy.dot()
- 두 벡터의 내적을 계산하는 함수
    - 내적이란 벡터에서 서로 대응하는 성분끼리 곱한다음 그것들을 모두 더한 것 을 말하며, 내적의 결과는 스칼라가 된다.
    - a·b 또는 <a,b>로 표현 : a1b1 + a2b2 + .... + anbn
- 행렬곱에도 사용될 수 있다
- 행렬곱이 이뤄지기 위해서는 첫 번째 행렬의 열크기와 두번째 행의 크기가 같아야한다


In [63]:
a = np.array([3,4,6,8,9])
b = np.array([7,3,1,4,7])
c = np.dot(a,b)
print(c)


134


In [67]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
print(a)
print(b)
print('-'*30)

print(np.dot(a,b)) # a.dot(b)와 동일
print(np.dot(b,a)) # 교환법칙이 성립되지 않는다

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
------------------------------
[[5 4]
 [3 4]]
[[2 2]
 [3 7]]


## numpy.matmul() / @ 연산자
- numpy.dot()을 이용하여 행렬곱을 수행할 수 있지만, numpy 공식 문서에서는 matmul() 사용을 권장(3차원 이상의 행렬곱에서는 연산의 결과가 다)

In [69]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

print(np.matmul(a,b))
print(a@b) # 파이썬 3.5버전 부터 가능

[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


## 전치(transpose)
- 전치는 기존 행렬과 행과 열을 교환 하는것. 즉, 주대각선을 기준으로 반사 대칭하는 것을 말한다.
- 배열 책체의 'T' 속성을 사용하거나 numpy.transpose()함수 이용

In [70]:
a = np.array([[1,2],[3,4]])
b = a.T
c = np.transpose(a)
print(a)
print(b)
print(c)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


# 인덱싱, 슬라이싱

## 인덱싱

In [73]:
a = np.arange(1,11).reshape(2,5)
print(a)
print(a[0,0])
print(a[0][0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
1


In [76]:
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]


### Boolean Indexing (masking)

In [88]:
a = np.arange(1,25).reshape(4,6)
print(a)

even_arr = a%2 ==0
print(even_arr)
print(np.sum(a[even_arr]))

print(np.sum(a[a%2 == 0]))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]
156
156


### Fancy Indexing
- 배열의 각 요소 선택을  **인덱스 배열을 전달하여** 참조하는 방식
- fancy indexing은 복사본이 생성된다.