# 붓꽃 분류

## 패키지 로딩

In [1]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB # 독립변수가 연속형인 경우
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix


## 데이터 로딩 및 분할

In [2]:
X, y = load_iris(return_X_y=True)
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=0,stratify=y)

## 모델 생성

In [3]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

## 모델 평가

In [4]:
y_hat = model.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test,y_hat):.3f}')


Accuracy: 0.967


In [6]:
con_mat = confusion_matrix(y_test,y_hat)
print(con_mat)

[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


# 독버섯 분류

## 패키지 로딩

In [4]:
from sklearn.naive_bayes import CategoricalNB # 독립변수가 연속형인 경우
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
import pandas as pd
import numpy as np

df = pd.read_csv('dataset/mushrooms.csv')
df

type cap_shape cap_surface cap_color bruises     odor   
0     poisonous    convex      smooth     brown     yes  pungent  \
1        edible    convex      smooth    yellow     yes   almond   
2        edible      bell      smooth     white     yes    anise   
3     poisonous    convex       scaly     white     yes  pungent   
4        edible    convex      smooth      gray      no     none   
...         ...       ...         ...       ...     ...      ...   
8119     edible   knobbed      smooth     brown      no     none   
8120     edible    convex      smooth     brown      no     none   
8121     edible      flat      smooth     brown      no     none   
8122  poisonous   knobbed       scaly     brown      no    fishy   
8123     edible    convex      smooth     brown      no     none   

     gill_attachment gill_spacing gill_size gill_color  ...   
0               free        close    narrow      black  ...  \
1               free        close     broad      black  ...   
2               free        close     broad      brown  ...   
3               free        close    narrow      brown  ...   
4               free      crowded     broad      black  ...   
...              ...          ...       ...        ...  ...   
8119        attached        close     broad     yellow  ...   
8120        attached        close     broad     yellow  ...   
8121        attached        close     broad      brown  ...   
8122            free        close    narrow       buff  ...   
8123        attached        close     broad     yellow  ...   

     stalk_surface_below_ring stalk_color_above_ring stalk_color_below_ring   
0                      smooth                  white                  white  \
1                      smooth                  white                  white   
2                      smooth                  white                  white   
3                      smooth                  white                  white   
4                      smooth                  white                  white   
...                       ...                    ...                    ...   
8119                   smooth                 orange                 orange   
8120                   smooth                 orange                 orange   
8121                   smooth                 orange                 orange   
8122                    silky                  white                  white   
8123                   smooth                 orange                 orange   

     veil_type veil_color ring_number   ring_type spore_print_color   
0      partial      white         one     pendant             black  \
1      partial      white         one     pendant             brown   
2      partial      white         one     pendant             brown   
3      partial      white         one     pendant             black   
4      partial      white         one  evanescent             brown   
...        ...        ...         ...         ...               ...   
8119   partial     orange         one     pendant              buff   
8120   partial      brown         one     pendant              buff   
8121   partial     orange         one     pendant              buff   
8122   partial      white         one  evanescent             white   
8123   partial     orange         one     pendant            orange   

     population  habitat  
0     scattered    urban  
1      numerous  grasses  
2      numerous  meadows  
3     scattered    urban  
4      abundant  grasses  
...         ...      ...  
8119  clustered   leaves  
8120    several   leaves  
8121  clustered   leaves  
8122    several   leaves  
8123  clustered   leaves  

[8124 rows x 23 columns]

In [16]:
X = df[1:]
y = df['type']
print(X.head())
print(y)
print(X.shape)
print(y.shape)

        type cap_shape cap_surface cap_color bruises     odor gill_attachment   
1     edible    convex      smooth    yellow     yes   almond            free  \
2     edible      bell      smooth     white     yes    anise            free   
3  poisonous    convex       scaly     white     yes  pungent            free   
4     edible    convex      smooth      gray      no     none            free   
5     edible    convex       scaly    yellow     yes   almond            free   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring   
1        close     broad      black  ...                   smooth  \
2        close     broad      brown  ...                   smooth   
3        close    narrow      brown  ...                   smooth   
4      crowded     broad      black  ...                   smooth   
5        close     broad      brown  ...                   smooth   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color   
1                  white  