# 공분산 행렬 구하기

In [2]:
import numpy as np

np.set_printoptions(precision=3,suppress=True)

In [9]:
x = [[177.7, 68.1, 91.8], [168, 60.2, 89.3], [165.3, 49.1, 84.9], [159.1, 42, 86.3], [176.4, 73.3, 93.8],
     [176, 57.2, 92.5], [170, 59.8, 89.8], [164.6, 51.6, 88.5], [174.4, 70.2, 91.7], [174.8, 58.8, 91.6]]
X =np.array(x)
print(X)
print('-'*50)
print('열평균', np.mean(X,axis=0))
X = X - np.mean(X,axis=0) # 각 컬럼의 편차 계산
print('-'*50)
print('[Coveriance]')
cov = X.T@X / (len(X) - 1)
print(cov)

[[177.7  68.1  91.8]
 [168.   60.2  89.3]
 [165.3  49.1  84.9]
 [159.1  42.   86.3]
 [176.4  73.3  93.8]
 [176.   57.2  92.5]
 [170.   59.8  89.8]
 [164.6  51.6  88.5]
 [174.4  70.2  91.7]
 [174.8  58.8  91.6]]
--------------------------------------------------
열평균 [170.63  59.03  90.02]
--------------------------------------------------
[Coveriance]
[[38.749 52.035 15.779]
 [52.035 95.54  23.158]
 [15.779 23.158  7.984]]


## np.cov() 결과 비교

In [10]:
np.cov(X, rowvar = False)

array([[38.749, 52.035, 15.779],
       [52.035, 95.54 , 23.158],
       [15.779, 23.158,  7.984]])

# 고유값, 고유벡터 행렬 구하기

In [28]:
eigenvalue, eigenvector = np.linalg.eig(cov)
print('고유값',eigenvalue)
print('-'*30)
print('고유값 대각 행렬')
eig_matrix = np.identity(3) * eigenvalue
print(eig_matrix)
print('-'*30)
print('고유벡터 행렬 V')
V = eigenvector
print(V)
print('첫 번째 고유벡터와 두번째 고유벡터와의 내적')
print(np.round(eigenvector[:,0].T.dot(eigenvector[:,1]),4))

print('-'*30)
print(cov)  # cov = X.T@X / (len(X) - 1)
print('-'*30)
print('고유벡터 행령@고유값 대각행렬@고유벡터 행렬의 역행렬')
print(V@eig_matrix@np.linalg.inv(V))


고유값 [132.696   8.307   1.27 ]
------------------------------
고유값 대각 행렬
[[132.696   0.      0.   ]
 [  0.      8.307   0.   ]
 [  0.      0.      1.27 ]]
------------------------------
고유벡터 행렬 V
[[-0.501 -0.803 -0.323]
 [-0.838  0.544 -0.054]
 [-0.219 -0.244  0.945]]
첫 번째 고유벡터와 두번째 고유벡터와의 내적
0.0
------------------------------
[[38.749 52.035 15.779]
 [52.035 95.54  23.158]
 [15.779 23.158  7.984]]
------------------------------
고유벡터 행령@고유값 대각행렬@고유벡터 행렬의 역행렬
[[38.749 52.035 15.779]
 [52.035 95.54  23.158]
 [15.779 23.158  7.984]]


# 첫번째 주성분(PC1) 구하기

In [30]:
pc1 = eigenvector[:,0].T@X.T
print(pc1)

[-11.526   0.494  12.106  20.85  -15.668  -1.699  -0.281   9.574 -11.61
  -2.241]


# 공분산을 이용한 주성분 분석

In [34]:
print('PCA를 이용한 차원 축소')
VT = np.array([eigenvector[:,0],eigenvector[:,1]])
print('고유벡터 VT - 주성분 2개 선택')
print(VT)
print("고유벡터 VT와 원 데이터 XT의 내적")
print((VT@X.T).T)

PCA를 이용한 차원 축소
고유벡터 VT - 주성분 2개 선택
[[-0.501 -0.838 -0.219]
 [-0.803  0.544 -0.244]]
고유벡터 VT와 원 데이터 XT의 내적
[[-11.526  -1.18 ]
 [  0.494   2.924]
 [ 12.106   0.129]
 [ 20.85    0.906]
 [-15.668   2.204]
 [ -1.699  -5.912]
 [ -0.281   0.978]
 [  9.574   1.173]
 [-11.61    2.637]
 [ -2.241  -3.859]]


# PCA 클래스와 결과 비교

In [38]:
from sklearn.decomposition import PCA

model = PCA(n_components=2)
pca = model.fit_transform(X)
print(pca.shape)
print(pca)

(10, 2)
[[-11.526   1.18 ]
 [  0.494  -2.924]
 [ 12.106  -0.129]
 [ 20.85   -0.906]
 [-15.668  -2.204]
 [ -1.699   5.912]
 [ -0.281  -0.978]
 [  9.574  -1.173]
 [-11.61   -2.637]
 [ -2.241   3.859]]


# PC(주성분)가 차지하는 분산 비율 구하기

In [40]:
var_ration = np.sum(eigenvalue[:2])/ np.sum(eigenvalue)
print(var_ration)
print(model.explained_variance_ratio_)
print(np.sum(model.explained_variance_ratio_))

0.9910760305908326
[0.933 0.058]
0.9910760305908327


# 고유벡터 행렬

In [42]:
# 고유벡터 행렬
model.components_

array([[-0.501, -0.838, -0.219],
       [ 0.803, -0.544,  0.244]])

In [43]:
# 고유값
model.explained_variance_

array([132.696,   8.307])