# Numpy

In [92]:
#1. 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성하고 각 행의 첫 번째 값으로 정렬하시오. (5점)
import numpy as np

a = np.random.randint(0,9,(3,3))
print(a)

a[a[:,0].argsort()]


[[4 4 4]
 [5 0 8]
 [8 2 1]]


array([[4, 4, 4],
       [5, 0, 8],
       [8, 2, 1]])

In [579]:
# 8x8 모양의 정수 0으로 채워진 행렬을 만들고 다음과 인덱싱과 슬라이싱일 이용하여 다음과 같은 체크보드 패턴을
# 만드시오. (10점)
a = np.zeros((8,8))

a[[0,2,4,6][:,[1,3,5,7]]]= 1
a


<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\user\AppData\Local\Temp\ipykernel_10572\2282898455.py:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a[[0,2,4,6][:,[1,3,5,7]]]= 1


TypeError: list indices must be integers or slices, not tuple

In [121]:
# [0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꾸는 코드를 만드시오. (5점)
f = np.random.rand(10)
f[:] =0
f.max()

0.0

월드컵 출전선수 골 기록 데이터 분석 (30점)
1. 데이터 파일: worldcupgoals.csv
2. 분석 내용
    - 주진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
    - 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.
    - Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케
    이스가 존재한다. 해당 건은 몇 건인지 출력하시오.
    - 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
    전체 데이터 행의 숫자를 출력하시오.
    - 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.
    - yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
    - 2002년도에 출전한 전체 선수 수를 구하시오.
    - 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [130]:
import pandas as pd
import numpy as np
#- 주진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
df = pd.read_csv('worldcupgoals.csv')
df

Player  Goals                Years     Country
0          Miroslav Klose     16  2002-2006-2010-2014     Germany
1                 Ronaldo     15       1998-2002-2006      Brazil
2             Gerd Muller     14            1970-1974     Germany
3           Just Fontaine     13                 1958      France
4                    Pele     12  1958-1962-1966-1970      Brazil
...                   ...    ...                  ...         ...
1290        Josip Skoblar      1                 1962  Yugoslavia
1291          Safet Susic      1            1982-1990  Yugoslavia
1292  Aleksandar Tirnanic      1                 1930  Yugoslavia
1293  Djordje Vujadinovic      1                 1930  Yugoslavia
1294         Branko Zebec      1            1954-1958  Yugoslavia

[1295 rows x 4 columns]

주진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
    

In [152]:
df['Country'].unique()
df.groupby('Country')['Goals'].sum().sort_values(ascending=False).head()


Country
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115
Name: Goals, dtype: int64

주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.

In [151]:
df.groupby('Country')['Player'].count().sort_values(ascending=False).head()

Country
Brazil       81
Germany      78
Italy        60
Argentina    59
France       58
Name: Player, dtype: int64

    - Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케
    이스가 존재한다. 해당 건은 몇 건인지 출력하시오.


In [177]:
df[df['Years'].str.replace('-','').astype('int64') <1000]


Player  Goals Years       Country
71             Roger Milla      5     0      Cameroon
190           Jesper Olsen      3     0       Denmark
210            Laszlo Kiss      3     0       Hungary
404         Ricardo Pelaez      2     0        Mexico
505          Djamel Zidane      1     0       Algeria
544         Andreas Herzog      1     0       Austria
622         Georgi Sokolov      1     0      Bulgaria
624           Eugene Ekeke      1     0      Cameroon
625             David Embe      1     0      Cameroon
640            Jose Sierra      1     0         Chile
651          Harold Lozano      1     0      Colombia
652        Leider Preciado      1     0      Colombia
662         Hernan Medford      1     0    Costa Rica
692           Milan Luhovy      1     0         Czech
699           John Eriksen      1     0       Denmark
705           Peter Moller      1     0       Denmark
713           Luis Ramirez      1     0   El Salvador
749     Christophe Dugarry      1     0        France
803         Andreas Moller      1     0       Germany
807           Uwe Reinders      1     0       Germany
825          Eduardo Laing      1     0      Honduras
835             Ferenc Sas      1     0       Hungary
837          Lazar Szentes      1     0       Hungary
841            Andras Toth      1     0       Hungary
854         Hassan Rowshan      1     0          Iran
856          John Aldridge      1     0       Ireland
895            Aldo Serena      1     0         Italy
899           Robbie Earle      1     0       Jamaica
913      Ignacio Basaguren      1     0        Mexico
952           Theo de Jong      1     0   Netherlands
959          Dick Nanninga      1     0   Netherlands
963         Gaston Taument      1     0   Netherlands
967   Pierre van Hooijdonk      1     0   Netherlands
985           Wilson Oruma      1     0       Nigeria
1025    Wlodzimierz Ciolek      1     0        Poland
1067    Fahad Al Ghesheyan      1     0  Saudi Arabia
1070     Youssef Al Tunian      1     0  Saudi Arabia
1119          Seo Jung Won      1     0   South Korea
1127     Txiki Begiristain      1     0         Spain
1134             Guardiola      1     0         Spain
1169       Glenn Stromberg      1     0        Sweden
1188           Jean Tamini      1     0   Switzerland
1214     Antonio Alzamendi      1     0       Uruguay
1216      Pablo Bengoechea      1     0       Uruguay
1268       Pavel Yakovenko      1     0          USSR

In [224]:
# - 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
#    전체 데이터 행의 숫자를 출력하시오.

In [391]:
df2 = df[df['Years'].str.replace('-','').astype('int64') >1000]
df2


Player  Goals                Years     Country
0          Miroslav Klose     16  2002-2006-2010-2014     Germany
1                 Ronaldo     15       1998-2002-2006      Brazil
2             Gerd Muller     14            1970-1974     Germany
3           Just Fontaine     13                 1958      France
4                    Pele     12  1958-1962-1966-1970      Brazil
...                   ...    ...                  ...         ...
1290        Josip Skoblar      1                 1962  Yugoslavia
1291          Safet Susic      1            1982-1990  Yugoslavia
1292  Aleksandar Tirnanic      1                 1930  Yugoslavia
1293  Djordje Vujadinovic      1                 1930  Yugoslavia
1294         Branko Zebec      1            1954-1958  Yugoslavia

[1250 rows x 4 columns]


    - 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.


In [392]:
a =df2['Years'].str.replace('-','').astype('int64')
#df2[np.logical_and(a>10000 ,a<100000000)] = 1
df2['LenCup'] = a
# df2[['LenCup'] < 10000] =1
c =df2[df2['LenCup']< 10000 ]
df2[df2['LenCup'] == df2['LenCup']< 10000] =1
b =df2[np.logical_and(df2['LenCup']> 10000,df2['LenCup']< 100000000)]
# df2
df2['LenCup'] = b['LenCup'] =2
df2

C:\Users\user\AppData\Local\Temp\ipykernel_10572\1854216850.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['LenCup'] = a


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

    - yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
    - 2002년도에 출전한 전체 선수 수를 구하시오.
    - 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [406]:
#yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
len(df2[np.logical_and(df2['Country'] == 'Yugoslavia',df2['LenCup'] >10000)])

8

In [427]:
#- 2002년도에 출전한 전체 선수 수를 구하시오.
df2['Years'].str.replace('2002','출전')
df2[df2['Years'] == '2002'].head()

Player  Goals Years  Country  LenCup
212  Robbie Keane      3  2002  Ireland    2002
228    Bouba Diop      3  2002  Senegal    2002
245  Ilhan Mansiz      3  2002   Turkey    2002
449  Henri Camara      2  2002  Senegal    2002
473   Umit Davala      2  2002   Turkey    2002

In [444]:
#월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.
df2[df2['LenCup']<10000][['Player','Goals']].sort_values(by=['Goals'],ascending=False).head(1)

Player  Goals
3  Just Fontaine     13

# 전 세계 행복도 지수 데이터 분석 (30점)

In [446]:
import pandas as pd
import numpy as np
df = pd.read_csv('happiness.csv')
df

행복랭킹                       나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도   
0       1                   Finland  7.769  1.340  1.587  0.986    0.596  \
1       2                   Denmark  7.600  1.383  1.573  0.996    0.592   
2       3                    Norway  7.554  1.488  1.582  1.028    0.603   
3       4                   Iceland  7.494  1.380  1.624  1.026    0.591   
4       5               Netherlands  7.488  1.396  1.522  0.999    0.557   
..    ...                       ...    ...    ...    ...    ...      ...   
307   152                     Yemen  3.355  0.442  1.073  0.343    0.244   
308   153                  Tanzania  3.303  0.455  0.991  0.381    0.481   
309   154               South Sudan  3.254  0.337  0.608  0.177    0.112   
310   155  Central African Republic  3.083  0.024  0.000  0.010    0.305   
311   156                   Burundi  2.905  0.091  0.627  0.145    0.065   

       관대함  부패에 대한인식    년도  
0    0.153     0.393  2019  
1    0.252     0.410  2019  
2    0.271     0.341  2019  
3    0.354     0.118  2019  
4    0.322     0.298  2019  
..     ...       ...   ...  
307  0.083     0.064  2018  
308  0.270     0.097  2018  
309  0.224     0.106  2018  
310  0.218     0.038  2018  
311  0.149     0.076  2018  

[312 rows x 10 columns]

- 1 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.


In [536]:
df.groupby(['년도']).head(10)

행복랭킹          나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도    관대함  부패에 대한인식   
0       1      Finland  7.769  1.340  1.587  0.986    0.596  0.153     0.393  \
1       2      Denmark  7.600  1.383  1.573  0.996    0.592  0.252     0.410   
2       3       Norway  7.554  1.488  1.582  1.028    0.603  0.271     0.341   
3       4      Iceland  7.494  1.380  1.624  1.026    0.591  0.354     0.118   
4       5  Netherlands  7.488  1.396  1.522  0.999    0.557  0.322     0.298   
5       6  Switzerland  7.480  1.452  1.526  1.052    0.572  0.263     0.343   
6       7       Sweden  7.343  1.387  1.487  1.009    0.574  0.267     0.373   
7       8  New Zealand  7.307  1.303  1.557  1.026    0.585  0.330     0.380   
8       9       Canada  7.278  1.365  1.505  1.039    0.584  0.285     0.308   
9      10      Austria  7.246  1.376  1.475  1.016    0.532  0.244     0.226   
156     1      Finland  7.632  1.305  1.592  0.874    0.681  0.202     0.393   
157     2       Norway  7.594  1.456  1.582  0.861    0.686  0.286     0.340   
158     3      Denmark  7.555  1.351  1.590  0.868    0.683  0.284     0.408   
159     4      Iceland  7.495  1.343  1.644  0.914    0.677  0.353     0.138   
160     5  Switzerland  7.487  1.420  1.549  0.927    0.660  0.256     0.357   
161     6  Netherlands  7.441  1.361  1.488  0.878    0.638  0.333     0.295   
162     7       Canada  7.328  1.330  1.532  0.896    0.653  0.321     0.291   
163     8  New Zealand  7.324  1.268  1.601  0.876    0.669  0.365     0.389   
164     9       Sweden  7.314  1.355  1.501  0.913    0.659  0.285     0.383   
165    10    Australia  7.272  1.340  1.573  0.910    0.647  0.361     0.302   

       년도  
0    2019  
1    2019  
2    2019  
3    2019  
4    2019  
5    2019  
6    2019  
7    2019  
8    2019  
9    2019  
156  2018  
157  2018  
158  2018  
159  2018  
160  2018  
161  2018  
162  2018  
163  2018  
164  2018  
165  2018

- 2 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.


In [539]:

df.groupby(['년도'])[['점수']].head(50).mean()

# happy.head(50)[['점수']].mean()

점수    6.6584
dtype: float64

- 3 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.
