# Numpy

In [2]:
#1. 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성하고 각 행의 첫 번째 값으로 정렬하시오. (5점)
import numpy as np

a = np.random.randint(0,9,(3,3))
print(a)

a[a[:,0].argsort()]


[[1 3 6]
 [1 2 4]
 [6 1 6]]


array([[1, 3, 6],
       [1, 2, 4],
       [6, 1, 6]])

In [6]:
# 8x8 모양의 정수 0으로 채워진 행렬을 만들고 다음과 인덱싱과 슬라이싱일 이용하여 다음과 같은 체크보드 패턴을
# 만드시오. (10점)
a = np.zeros((8,8))

a[1::2,::2]= 1
a[::2,1::2] =1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [11]:
# [0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고 최대값을 0으로 바꾸는 코드를 만드시오. (5점)
f = np.random.rand(10)

f[f.argmax()]=0
print(f)

[0.79394678 0.43989373 0.15171158 0.66623642 0.30871439 0.28560276
 0.27197439 0.56703346 0.         0.04712944]


월드컵 출전선수 골 기록 데이터 분석 (30점)
1. 데이터 파일: worldcupgoals.csv
2. 분석 내용
    - 주진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
    - 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.
    - Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케
    이스가 존재한다. 해당 건은 몇 건인지 출력하시오.
    - 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
    전체 데이터 행의 숫자를 출력하시오.
    - 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.
    - yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
    - 2002년도에 출전한 전체 선수 수를 구하시오.
    - 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [13]:
import pandas as pd
import numpy as np
#- 주진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
df = pd.read_csv('worldcupgoals.csv')
df

Player  Goals                Years     Country
0          Miroslav Klose     16  2002-2006-2010-2014     Germany
1                 Ronaldo     15       1998-2002-2006      Brazil
2             Gerd Muller     14            1970-1974     Germany
3           Just Fontaine     13                 1958      France
4                    Pele     12  1958-1962-1966-1970      Brazil
...                   ...    ...                  ...         ...
1290        Josip Skoblar      1                 1962  Yugoslavia
1291          Safet Susic      1            1982-1990  Yugoslavia
1292  Aleksandar Tirnanic      1                 1930  Yugoslavia
1293  Djordje Vujadinovic      1                 1930  Yugoslavia
1294         Branko Zebec      1            1954-1958  Yugoslavia

[1295 rows x 4 columns]

주진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와 그 득점수를 출력하시오
    

In [14]:
df['Country'].unique()
df.groupby('Country')['Goals'].sum().sort_values(ascending=False).head()
df.groupby('Country')[['Goals']].sum().sort_values('Goals',ascending=False).head()

Goals
Country         
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115

주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라 상위 5개 국가와 그 선수 숫자를 출력하시오.

In [151]:
df.groupby('Country')['Player'].count().sort_values(ascending=False).head()

Country
Brazil       81
Germany      78
Italy        60
Argentina    59
France       58
Name: Player, dtype: int64

    - Years 컬럼은 년도 -년도 형식으로 구성 되어있고, 각 년도는 4자리 숫자이다. 각 년도 표기가 4자리 숫자로 안된 케
    이스가 존재한다. 해당 건은 몇 건인지 출력하시오.


In [17]:
# df[df['Years'].str.replace('-','').astype('int64') <1000]
count = 0
for years in df['Years']:
    for year in years.split('-'):
        if len(year) != 4:
            count += 1
print(count)


45


In [224]:
# - 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)를 제외한 새로운 데이터 프레임을 생성하고
#    전체 데이터 행의 숫자를 출력하시오.

In [20]:
# df2 = df[df['Years'].str.replace('-','').astype('int64') >1000]
# df2

def checkYearFormat(years):
    for year in years.split('-'):
        if len(year) != 4:
            return False
    return True

df['year_check'] = df['Years'].apply(lambda x : checkYearFormat(x))
check =df['year_check'] ==False
check.sum()
df_new = df[df['year_check']]
df_new.shape[0]

1250


    - 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.


In [24]:
# a =df2['Years'].str.replace('-','').astype('int64')
# #df2[np.logical_and(a>10000 ,a<100000000)] = 1
# df2['LenCup'] = a
# # df2[['LenCup'] < 10000] =1
# c =df2[df2['LenCup']< 10000 ]
# df2[df2['LenCup'] == df2['LenCup']< 10000] =1
# b =df2[np.logical_and(df2['LenCup']> 10000,df2['LenCup']< 100000000)]
# # df2
# df2['LenCup'] = b['LenCup'] =2
# df2
import warnings
warnings.filterwarnings(action='ignore')
df_new['LenCup'] = [len(years.split('-')) for years in df_new['Years']]
len(df_new[df_new['LenCup'] == 4])


16

    - yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
    - 2002년도에 출전한 전체 선수 수를 구하시오.
    - 월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.

In [406]:
#yugoslavia 국가의 월드컵 출전횟수가 2회인 선수들의 숫자를 구하시오.
len(df2[np.logical_and(df2['Country'] == 'Yugoslavia',df2['LenCup'] >10000)])

8

In [25]:
#- 2002년도에 출전한 전체 선수 수를 구하시오.
# df2['Years'].str.replace('2002','출전')
# df2[df2['Years'] == '2002'].head()
len(df_new[df_new['Years'].str.contains('2002')])

156

In [444]:
#월드컵 출전 횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.
df2[df2['LenCup']<10000][['Player','Goals']].sort_values(by=['Goals'],ascending=False).head(1)

Player  Goals
3  Just Fontaine     13

# 전 세계 행복도 지수 데이터 분석 (30점)

In [28]:
import pandas as pd
import numpy as np
df = pd.read_csv('happiness.csv')
df

행복랭킹                       나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도   
0       1                   Finland  7.769  1.340  1.587  0.986    0.596  \
1       2                   Denmark  7.600  1.383  1.573  0.996    0.592   
2       3                    Norway  7.554  1.488  1.582  1.028    0.603   
3       4                   Iceland  7.494  1.380  1.624  1.026    0.591   
4       5               Netherlands  7.488  1.396  1.522  0.999    0.557   
..    ...                       ...    ...    ...    ...    ...      ...   
307   152                     Yemen  3.355  0.442  1.073  0.343    0.244   
308   153                  Tanzania  3.303  0.455  0.991  0.381    0.481   
309   154               South Sudan  3.254  0.337  0.608  0.177    0.112   
310   155  Central African Republic  3.083  0.024  0.000  0.010    0.305   
311   156                   Burundi  2.905  0.091  0.627  0.145    0.065   

       관대함  부패에 대한인식    년도  
0    0.153     0.393  2019  
1    0.252     0.410  2019  
2    0.271     0.341  2019  
3    0.354     0.118  2019  
4    0.322     0.298  2019  
..     ...       ...   ...  
307  0.083     0.064  2018  
308  0.270     0.097  2018  
309  0.224     0.106  2018  
310  0.218     0.038  2018  
311  0.149     0.076  2018  

[312 rows x 10 columns]

- 1 각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.


In [29]:
# df.groupby(['년도']).head(10)
df[df['행복랭킹'] <= 10].groupby('년도')['점수'].mean()

년도
2018    7.4442
2019    7.4559
Name: 점수, dtype: float64

- 2 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.


In [539]:

df.groupby(['년도'])[['점수']].head(50).mean()

# happy.head(50)[['점수']].mean()

점수    6.6584
dtype: float64

- 3 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.


In [31]:
grouped = df.groupby('년도')
for year, group in grouped:
    print(year,'년도: ', end='')
    print(group[group['행복랭킹']<= 10]['점수'].mean())

2018 년도: 7.4442
2019 년도: 7.4559


In [33]:
df[df['행복랭킹']<=50].groupby('년도')[['점수']].mean()

점수
년도           
2018  6.64678
2019  6.67002

## 각 연도별 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오

In [35]:
df.sort_values(['년도','점수']).groupby('년도').head(5).groupby('년도')['점수'].mean()

년도
2018    3.1800
2019    3.1408
Name: 점수, dtype: float64

In [38]:
df_2019 = df[df['년도'] == 2019]
over_mean = df_2019[df_2019['상대GDP'] >= df_2019['상대GDP'].mean()]['점수'].mean()
under_mean = df_2019[df_2019['상대GDP'] < df_2019['상대GDP'].mean()]['점수'].mean()
over_mean -under_mean

1.390483957219251

In [42]:
df.sort_values(['년도','부패에 대한인식'],ascending=False).groupby('년도').head(20).groupby('년도')['부패에 대한인식'].mean()

년도
2018    0.3267
2019    0.3201
Name: 부패에 대한인식, dtype: float64

In [47]:
df1 = df[np.logical_and(df['년도'] == 2018, df['행복랭킹']<= 50 )]['나라명']
df1
df2 =df[np.logical_and(df['년도'] == 2019, df['행복랭킹']> 50 )]['나라명']
df2
df2[df2.isin(df1)]

50      Kuwait
51    Thailand
79    Malaysia
Name: 나라명, dtype: object

In [58]:
year_2018 = df[df['년도'] == 2018]['나라명']
year_2019 = df[df['년도'] == 2019]['나라명']
year_2018_2019 =year_2019[year_2019.isin(year_2018)]
year_2018_2019


0                       Finland
1                       Denmark
2                        Norway
3                       Iceland
4                   Netherlands
                 ...           
151                      Rwanda
152                    Tanzania
153                 Afghanistan
154    Central African Republic
155                 South Sudan
Name: 나라명, Length: 152, dtype: object

In [59]:
multiple = df[df['나라명'].isin(year_2018_2019)]
multiple

행복랭킹                       나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도   
0       1                   Finland  7.769  1.340  1.587  0.986    0.596  \
1       2                   Denmark  7.600  1.383  1.573  0.996    0.592   
2       3                    Norway  7.554  1.488  1.582  1.028    0.603   
3       4                   Iceland  7.494  1.380  1.624  1.026    0.591   
4       5               Netherlands  7.488  1.396  1.522  0.999    0.557   
..    ...                       ...    ...    ...    ...    ...      ...   
307   152                     Yemen  3.355  0.442  1.073  0.343    0.244   
308   153                  Tanzania  3.303  0.455  0.991  0.381    0.481   
309   154               South Sudan  3.254  0.337  0.608  0.177    0.112   
310   155  Central African Republic  3.083  0.024  0.000  0.010    0.305   
311   156                   Burundi  2.905  0.091  0.627  0.145    0.065   

       관대함  부패에 대한인식    년도  
0    0.153     0.393  2019  
1    0.252     0.410  2019  
2    0.271     0.341  2019  
3    0.354     0.118  2019  
4    0.322     0.298  2019  
..     ...       ...   ...  
307  0.083     0.064  2018  
308  0.270     0.097  2018  
309  0.224     0.106  2018  
310  0.218     0.038  2018  
311  0.149     0.076  2018  

[304 rows x 10 columns]

In [65]:
year_2018 = multiple[multiple['년도'] == 2018].sort_values('나라명')
year_2019 = multiple[multiple['년도'] == 2019].sort_values('나라명')
year_2018.reset_index(drop=True,inplace=True)
year_2019.reset_index(drop=True,inplace=True)

year_2019['전년대비 점수 증가'] = year_2019['점수'] - year_2018['점수']
year_2019
year_2019[year_2019['전년대비 점수 증가'].max() == year_2019['전년대비 점수 증가']][['나라명','전년대비 점수 증가']]
# year_2019['전년대비 점수 증가'] = year_2019['점수'].values - year_2018['점수'].values
# year_2019
# year_2019[year_2019['전년대비 점수 증가'].max() == year_2019['전년대비 점수 증가']][['나라명','전년대비 점수 증가']]

나라명  전년대비 점수 증가
20  Burundi        0.87

# 유튜브

In [66]:
df = pd.read_csv('youtube_rank.csv')
df

title    category subscriber       view    video
0                      BLACKPINK  [음악/댄스/가수]      5140만  128억5130만     319개
1                 Big Hit Labels  [음악/댄스/가수]      4550만  120억8966만     433개
2                      BANGTANTV  [음악/댄스/가수]      3870만   54억7598만   1,319개
3    Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]      2650만  110억5288만     223개
4                         SMTOWN  [음악/댄스/가수]      2450만  180억7532만   3,583개
..                           ...         ...        ...        ...      ...
995                Ranking World       [미분류]        40만    1억2752만     503개
996                         급식걸즈    [취미/라이프]        40만    2억3901만     226개
997                          OCN     [TV/방송]        40만    3억4583만  10,071개
998                Bravo jamoasi       [미분류]        40만      6193만      25개
999                  덕출 : DCTVGO     [TV/방송]        40만      8249만     202개

[1000 rows x 5 columns]

In [73]:
df.columns = ['채널명','카테고리','구독자수','조회수','영상개수']
df.head()

채널명        카테고리      구독자수          조회수  영상개수
0                    BLACKPINK  [음악/댄스/가수]  51400000  12851300000   319
1               Big Hit Labels  [음악/댄스/가수]  45500000  12089660000   433
2                    BANGTANTV  [음악/댄스/가수]  38700000   5475980000  1319
3  Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  11052880000   223
4                       SMTOWN  [음악/댄스/가수]  24500000  18075320000  3583

In [70]:
df['구독자수'] = df['구독자수'].str.replace('만','0000',regex=False).astype('int64')

채널명        카테고리      구독자수        조회수     영상개수
0                      BLACKPINK  [음악/댄스/가수]  51400000  128억5130만     319개
1                 Big Hit Labels  [음악/댄스/가수]  45500000  120억8966만     433개
2                      BANGTANTV  [음악/댄스/가수]  38700000   54억7598만   1,319개
3    Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  110억5288만     223개
4                         SMTOWN  [음악/댄스/가수]  24500000  180억7532만   3,583개
..                           ...         ...       ...        ...      ...
995                Ranking World       [미분류]    400000    1억2752만     503개
996                         급식걸즈    [취미/라이프]    400000    2억3901만     226개
997                          OCN     [TV/방송]    400000    3억4583만  10,071개
998                Bravo jamoasi       [미분류]    400000      6193만      25개
999                  덕출 : DCTVGO     [TV/방송]    400000      8249만     202개

[1000 rows x 5 columns]

In [71]:
df['조회수'] = df['조회수'].replace(['억','만'],['','0000'],regex = True).astype('int64')
df

채널명        카테고리      구독자수          조회수     영상개수
0                      BLACKPINK  [음악/댄스/가수]  51400000  12851300000     319개
1                 Big Hit Labels  [음악/댄스/가수]  45500000  12089660000     433개
2                      BANGTANTV  [음악/댄스/가수]  38700000   5475980000   1,319개
3    Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  11052880000     223개
4                         SMTOWN  [음악/댄스/가수]  24500000  18075320000   3,583개
..                           ...         ...       ...          ...      ...
995                Ranking World       [미분류]    400000    127520000     503개
996                         급식걸즈    [취미/라이프]    400000    239010000     226개
997                          OCN     [TV/방송]    400000    345830000  10,071개
998                Bravo jamoasi       [미분류]    400000     61930000      25개
999                  덕출 : DCTVGO     [TV/방송]    400000     82490000     202개

[1000 rows x 5 columns]

In [72]:
df['영상개수'] = df['영상개수'].replace([',','개'],['',''],regex = True).astype('int32')

In [74]:
df.sort_values('구독자수',ascending=False).head()

채널명        카테고리      구독자수          조회수  영상개수
0                    BLACKPINK  [음악/댄스/가수]  51400000  12851300000   319
1               Big Hit Labels  [음악/댄스/가수]  45500000  12089660000   433
2                    BANGTANTV  [음악/댄스/가수]  38700000   5475980000  1319
3  Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  11052880000   223
4                       SMTOWN  [음악/댄스/가수]  24500000  18075320000  3583

In [75]:
df.sort_values('조회수',ascending=False).head()


채널명        카테고리      구독자수          조회수   영상개수
4            SMTOWN  [음악/댄스/가수]  24500000  18075320000   3583
6      1theK (원더케이)  [음악/댄스/가수]  20900000  17860420000  13291
8  ArianaGrandeVevo  [음악/댄스/가수]  18200000  14796920000    112
0         BLACKPINK  [음악/댄스/가수]  51400000  12851300000    319
1    Big Hit Labels  [음악/댄스/가수]  45500000  12089660000    433

In [76]:
df[df['카테고리']== '[음악/댄스/가수]'].sort_values('구독자수', ascending=False).head()

채널명        카테고리      구독자수          조회수  영상개수
0              BLACKPINK  [음악/댄스/가수]  51400000  12851300000   319
1         Big Hit Labels  [음악/댄스/가수]  45500000  12089660000   433
2              BANGTANTV  [음악/댄스/가수]  38700000   5475980000  1319
4                 SMTOWN  [음악/댄스/가수]  24500000  18075320000  3583
5  1MILLION Dance Studio  [음악/댄스/가수]  22300000   5753580000  2205

In [78]:
len(df[df['카테고리'].isin(['[TV/방송]','[게임]'])])

262

In [80]:
df[df['채널명'].str.contains('KBS')]['채널명']

12                    KBS World
46                     KBS Kpop
76                KBS Entertain
101                   KBS Drama
290                    KBS 한국방송
292           KBS Drama Classic
308             KBS HUMAN: 뭉클티비
389                    KBS News
457                  KBS CoolFM
716                       KBS N
777                    KBS KONG
991    KBS Documentary [KBS 다큐]
992                      KBS 교양
Name: 채널명, dtype: object

In [82]:
df.groupby('카테고리')[['구독자수','조회수','영상개수']].mean().round(2)

구독자수           조회수      영상개수
카테고리                                           
[BJ/인물/연예인]  1274411.76  4.101549e+08    837.74
[IT/기술/컴퓨터]   806250.00  1.766100e+08   1200.12
[TV/방송]      1219875.78  7.184834e+08   9025.13
[게임]          743564.36  4.542535e+08   2527.01
[교육/강의]       851304.35  1.772183e+08    837.91
[국내/해외/여행]    626000.00  1.866240e+08    830.20
[뉴스/정치/사회]   1226964.29  1.199936e+09  42048.09
[미분류]        1429500.00  4.090340e+08    778.05
[스포츠/운동]      932500.00  2.791892e+08   3954.92
[애완/반려동물]    1161000.00  4.213170e+08    786.25
[영화/만화/애니]    852727.27  3.185870e+08    770.18
[음식/요리/레시피]  1612045.45  4.073819e+08    830.02
[음악/댄스/가수]   3195200.00  1.091668e+09   1382.05
[자동차]         490000.00  1.856150e+08    670.00
[주식/경제/부동산]   626000.00  6.800000e+07   1026.40
[취미/라이프]      974500.00  2.043118e+08    359.32
[취미]          560000.00  1.061500e+08    237.00
[키즈/어린이]     2729157.89  1.281384e+09   1069.16
[패션/미용]       823859.65  1.043774e+08    313.16
[해외]         1595000.00  8.382533e+08   5043.50
[회사/오피셜]     2202500.00  4.966125e+08   2084.25