# [문제] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사람별 BMI 지수를 구하고 비만 전단계 이상인 BMI 값 확인하기

<pre>
 BMI 지수 = 몸무게(kg) / 키(M)의 제곱
 체질량지수의 범위 값에 따른 비만도 값 지정
 18.5 미만 ▶ 저체중
 18.5 ~ 22.9 ▶ 정상
 23 ~ 24.9 ▶ 비만 전단계
 25 ~ 29 ▶ 1단계 비만
 30 ~ 34.9 ▶ 2단계 비만
 35이상 ▶ 고도비만
</pre>

In [12]:
import numpy as np

data = np.loadtxt('height_weight.txt', delimiter=',', dtype = float)
print(data)
a = (data[0]/100)**2

print(a)
weight = data[1]/a
print(weight)
#np.where(data[1]/a >18.5,"저체중")

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]
[3.069504 3.250809 3.0625   2.862864 3.429904 3.5344   3.154176 3.175524
 3.1329   3.2041  ]
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


# [문제] 국가건강검진 혈압혈당 데이터 분석

* '국가건강검진_혈압혈당데이터.csv' 파일 내용을 읽기 <data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float, skiprows=1)>
    - 성별: 1(남자), 2(여자)
    - 연령그룹: 1(20-24), 2(25-26),...25-74세까지 2살 간격으로 1개 그룹으로 지정, 27(74세 이상)
    - 고혈압 당뇨병 진료여부: 1(고혈압 및 당뇨진료내역 있음), 2(고혈압 진료내역 있음), 3(당뇨 진료내역 있음), 4(고혈압 및 당뇨 진료내역 없음)
    - 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
    - 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
* 전체 레코드 수와 상위 5개 데이터 확인
* 데이터 모양 확인
* 여성과 남성의 데이터 수 확인
* 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
* 정상 혈압 남자 및 여자 수 확인
* 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수

In [120]:
import numpy as np
data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",",dtype=float, skiprows=1)
print(data[:5])
print(data.shape)
man = data[:,0] ==1
woman = data[:,0] ==2
print(man)
print(len(data[man]))
print(len(data[woman]))

print(np.average(data[man][:,2]))
print(np.average(data[man][:,3]))
print(np.average(data[woman][:,2]))
print(np.average(data[woman][:,3]))

# jungsangSu = data[:,2] < 120 
# jungsangHw = data[:,3] < 80
# jungsang = data[np.logical_and(jungsangHw,jungsangSu)]
# jungsangdata = data[jungsang]
# print(jungsangdata)
# print(len(jungsangdata[:,0]==1))
print("-"*50)

nbp_masking = np.logical_and(data[:,2] < 120,data[:,3] < 80)
nbp_data = data[nbp_masking]
print(f'정상혈압 남자 수: {sum(nbp_data[:,0]==1)}')
print(f'정상혈압 여자 수: {sum(nbp_data[:,0]==2)}')

diabetes = data[data[:,4] >= 126]
print(f'당뇨병 질환 환자의 평균 BMI: {np.mean(diabetes[:,6]):.2f}')
# print(data)


[[  1.    1.  116.   78.   94.    4.   16.6]
 [  1.    1.  100.   60.   79.    4.   22.3]
 [  1.    1.  100.   60.   87.    4.   21.9]
 [  1.    1.  111.   70.   72.    4.   20.2]
 [  1.    1.  120.   80.   98.    4.   20. ]]
(1000000, 7)
[ True  True  True ... False False False]
510227
489773
124.2799538244742
77.61497725522169
119.36300081874664
73.88446688567969
--------------------------------------------------
정상혈압 남자 수: 158007
정상혈압 여자 수: 230707
당뇨병 질환 환자의 평균 BMI: 25.17


In [ ]:
man_sbp_mean = np.mean(data[data[:,0] == 1][:,2])

# [문제] 시에틀 강수량 데이터 분석
- 'Seattle2014.csv' 파일 내용 읽기
- 강수량('PRCP')이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균강수량 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

In [203]:
data = np.loadtxt('Seattle2014.csv',delimiter=',', dtype=object, skiprows=1)
#print(data[:5])
data =data[:,3].astype(dtype=float)
sorted_data = np.sort(data)[::-1]
print(sorted_data[:10])

january = data[:31]
print(january)
print(np.sum(january))
print(np.mean(january))

# nbp_masking = np.logical_and(data[:,2] < 120,data[:,3] < 80)
# nbp_data = data[nbp_masking]
# print(f'정상혈압 남자 수: {sum(nbp_data[:,0]==1)}')




[467. 343. 333. 323. 320. 277. 264. 254. 221. 216.]
[  0.  41.  15.   0.   0.   3. 122.  97.  58.  43. 213.  15.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   5.   0.   0.   0.   0.   0.  89.
 216.   0.  23.]
940.0
30.322580645161292


In [190]:
print(len(data))
a = data <40 
print(len(data[a]))
b = data != 0 
cdata = np.logical_and(a,b)
ddata = data[cdata]
print(ddata)
print(len(ddata))

365
277
[15.  3. 15.  5. 23. 20.  5. 18. 10. 30. 28. 25.  3.  5. 30.  5.  3.  5.
 36.  3. 25.  5. 33. 20.  5. 38. 18.  5. 36. 13.  8.  3. 18. 23.  3.  5.
  5. 10. 13. 30.  5.  3.  3.  8.  3. 33. 10. 15.  8.  5. 18. 36.  5. 13.
  3. 33. 36.  8. 30. 28. 30. 33.]
62


In [208]:
#1월 강수량
data = np.loadtxt('Seattle2014.csv',delimiter=',', dtype=object, skiprows=1)

prcp = data[ :,[2,3]]
prcp_month = np.array([[date[4:6],prcp] for date,prcp in prcp])
jan_prcp = prcp_month[prcp_month[:,0] == '01'][:,1].astype(int)
print(jan_prcp)

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


# [문제] 영화 평점 분석
- 'ratings.dat' 파일 내용 읽기 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인(크기, 차원)
- 전체 데이터 평점 구하기
- 사용자 아이디 1인 데이터 출력하기
- 사용자 아이디 1인 사람의 평점 평균 구하기
- 각 사용자별 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

In [41]:
import numpy as np
data = np.loadtxt('ratings.dat', delimiter=":", dtype=np.int32)
# print(data)
print(data.shape)
print(np.mean(data[:,2]))

user1 = data[:,0] ==1
print(np.mean(data[user1][:,2]))

user_ids = np.unique(data[:,0])
# a = data[:,0] == user_ids
# print(user_ids)
user_avg_ratings = [[id,np.mean(data[data[:,0] == id][:,2])]for id in user_ids]
for id,avg_rating in user_avg_ratings[:10]:
    print(f'{id} : {avg_rating:.2f}점')
# print(np.mean(data[a][:,2]))



(1000209, 4)
3.581564453029317
4.188679245283019
1 : 4.19점
2 : 3.71점
3 : 3.90점
4 : 4.19점
5 : 3.15점
6 : 3.90점
7 : 4.32점
8 : 3.88점
9 : 3.74점
10 : 4.11점
[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606]]


In [45]:
user_avg_rating = np.array(user_avg_ratings)
user_avg_rating[:10]
print(f'평균 평점이 4점 이상인 유저수 : {sum(user_avg_rating[:,1]>= 4):,} 명')

평균 평점이 4점 이상인 유저수 : 1,544 명
